name: Build and publish sanity types

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      SKIP_YARN_COREPACK_CHECK: true
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-node@v4'
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
      - name: Enable Corepack
        run: corepack enable
      - name: 'install dependencies'
        run: 'yarn --immutable'
      - name: 'Generate types'
        run: 'yarn generateSchemaTypes'
      - name: 'Login'
        run: |
          git config user.email "aap-innbygger@nav.no"
          git config user.name "Team Innbygger"
          git remote set-url origin https://github-actions[bot]:$GITHUB_TOKEN@github.com/navikt/aap-felles-innbygger.git
          git fetch origin
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Create a .npmrc file for the github package repository'
        uses: 'FerLuisxd/create-npmrc@3'
        with:
          org_name: 'navikt'
        env:
          AUTH_TOKEN: '${{secrets.GITHUB_TOKEN}}'
      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset publish
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
